import {
  KE,
  UG,
  TZ,
  RW,
  BI,
  ZM,
  ZW,
  ZA,
  MZ,
  NA,
  MW,
  BW,
} from "country-flag-icons/react/3x2";

export type Country = {
  name: string;
  active: boolean;
  code: string;
  currency: string;
  language: string;
  capital: string;
  flag: React.ReactNode;
  region: string;
  exchangeRateToUSD: number;
};

const Countries: Country[] = [
  {
    name: "Kenya",
    active: true,
    code: "ke",
    currency: "KES",
    language: "English, Swahili",
    capital: "Nairobi",
    flag: <KE />, // <KE/> is a react component from the country-flag-icons package
    region: "Africa",
    exchangeRateToUSD: 0.009,
  },
  {
    name: "Uganda",
    active: false,
    code: "ug",
    currency: "UGX",
    language: "English",
    capital: "Kampala",
    flag: <UG />,
    region: "Africa",
    exchangeRateToUSD: 0.00027,
  },
  {
    name: "Tanzania",
    active: true,
    code: "tz",
    currency: "TZS",
    language: "English, Swahili",
    capital: "Dodoma",
    flag: <TZ />,
    region: "Africa",
    exchangeRateToUSD: 0.00044,
  },
  {
    name: "Rwanda",
    active: false,
    code: "rw",
    currency: "RWF",
    language: "English, French, Kinyarwanda",
    capital: "Kigali",
    flag: <RW />,
    region: "Africa",
    exchangeRateToUSD: 0.0011,
  },
  {
    name: "Burundi",
    active: false,
    code: "bi",
    currency: "BIF",
    language: "French, Kirundi",
    capital: "Bujumbura",
    flag: <BI />,
    region: "Africa",
    exchangeRateToUSD: 0.00059,
  },
  {
    name: "Zambia",
    active: true,
    code: "zm",
    currency: "ZMW",
    language: "English",
    capital: "Lusaka",
    flag: <ZM />,
    region: "Africa",
    exchangeRateToUSD: 0.13,
  },
  {
    name: "Zimbabwe",
    active: false,
    code: "zw",
    currency: "ZWL",
    language: "English, Shona, Sindebele",
    capital: "Harare",
    flag: <ZW />,
    region: "Africa",
    exchangeRateToUSD: 0.0001,
  },
  {
    name: "South Africa",
    active: false,
    code: "za",
    currency: "ZAR",
    language: "English, Afrikaans, Zulu, Xhosa, Sotho",
    capital: "Pretoria",
    flag: <ZA />,
    region: "Africa",
    exchangeRateToUSD: 0.065,
  },
  {
    name: "Mozambique",
    active: false,
    code: "mz",
    currency: "MZN",
    language: "Portuguese",
    capital: "Maputo",
    flag: <MZ />,
    region: "Africa",
    exchangeRateToUSD: 0.014,
  },
  {
    name: "Namibia",
    active: true,
    code: "na",
    currency: "NAD",
    language: "English, Afrikaans",
    capital: "Windhoek",
    flag: <NA />,
    region: "Africa",
    exchangeRateToUSD: 0.065,
  },
  {
    name: "Malawi",
    active: false,
    code: "mw",
    currency: "MWK",
    language: "English, Chichewa",
    capital: "Lilongwe",
    flag: <MW />,
    region: "Africa",
    exchangeRateToUSD: 0.0014,
  },
  {
    name: "Botswana",
    active: true,
    code: "bw",
    currency: "BWP",
    language: "English, Tswana",
    capital: "Gaborone",
    flag: <BW />,
    region: "Africa",
    exchangeRateToUSD: 0.11,
  },
  {
    name: "Greece",
    active: true,
    code: "gr",
    currency: "EUR",
    language: "Greek",
    capital: "Athens",
    flag: <BW />,
    region: "Europe",
    exchangeRateToUSD: 1.18,
  },
];

export default Countries;
